---
name: Build html & Publish to github pages

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: install node requirements
        run: make node_modules
      - name: build html
        run: |
          sed -i "s/href='/href='\/analytics-google/"  public/index.html
          sed -i "s/src='/src='\/analytics-google/"  public/index.html
          make build
        env:
          MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
          BASEURL: '/analytics-google'
      - name: deploy to github pages
        if: success() && steps.extract_branch.outputs.branch == 'master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: gh-pages
          publish_dir: ./public
