---
name: Build html & Publish to github pages

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: install node requirements
        run: make node_modules
      - name: build html
        run: |
          sed -i "s/href='/href='\/analytics-google/"  public/index.html
          sed -i "s/src='/src='\/analytics-google/"  public/index.html
          make build
        env:
          MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
          BASEURL: '/analytics-google'
      - name: deploy to github pages
        if: success() && steps.extract_branch.outputs.branch == 'master'
        # uses: peaceiris/actions-gh-pages@v2.2.0
        uses: docker://peaceiris/gh-pages:v2.3.2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public
