---
name: Get data from GA

on: [push]
#on:
#  schedule:
#    # * is a special character in YAML so you have to quote this string
#    - cron:  '57 21 * * *'

jobs:
  publish:
    name: Get data from GA
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: install python requirements
        run: make venv
      - name: get data
        run: make data
        env:
          TOKEN: ${{ secrets.TOKEN }}
      - name: deploy to github pages
        if: success()
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: data
          directory: public/data
