---
name: Get data from GA

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '57 21 * * *'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: install python requirements
        run: make venv
      - name: get data
        run: make data
        env:
          TOKEN: ${{ secrets.TOKEN }}
      - name: deploy to github pages
        if: success()
        uses: docker://peaceiris/gh-pages:v2.3.2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: data
          PUBLISH_DIR: public/data
