---
name: Build html

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '57 21 * * *'
  push:
    branches:
    - master

jobs:
  publish:
    name: Publish github pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: install python requirements
        run: make venv
      - name: get data
        run: make data
        env:
          TOKEN: ${{ secrets.TOKEN }}
      - name: install node requirements
        run: make node_modules
      - name: build html
        run: make build
        env:
          MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
      - name: deploy to github pages
        # uses: peaceiris/actions-gh-pages@v2.2.0
        uses: docker://peaceiris/gh-pages:v2.3.2
        if: success()
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public
